[build]
  command = "pip install -r requirements.txt"
  functions = "api"

[functions]
  included_files = ["template_clean.jpg"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true
